spring:
    application:
        name: ai-service
    data:
        mongodb:
            uri: mongodb://localhost:27017/fitnessRecommendation
            database: fitnessRecommendation

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

server:
    port: 8083